
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['SOUFFLE_DATABASE_NANE'] %>
  username: <%= ENV['SOUFFLE_DATABASE_USER_NAME'] %>
  password: <%= ENV['SOUFFLE_DATABASE_PASSWORD'] %>
  host: <%= ENV['SOUFFLE_DATABASE_HOST'] %>
  
development:
  <<: *default

test:
  <<: *default
  database: souffle_test

production:
  <<: *default
